### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by chesal** [Bone008/finance-tracker#123]
When running the build command : 

`npm run ng build`

I have the following errors, any idea how can I solve this ?

`
chunk {main} main.js, main.js.map (main) 626 bytes [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 92.4 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 182 kB [initial] [rendered]

ERROR in src/app/money/billing-info/billing-info.component.ts(46,23): error TS2709: Cannot use namespace 'BillingType' as a type.
src/app/money/billing-info/billing-info.component.ts(50,27): error TS2709: Cannot use namespace 'BillingType' as a type.
src/app/money/model-util.ts(263,76): error TS2709: Cannot use namespace 'BillingType' as a type.
src/app/money/rule.service.ts(46,71): error TS2709: Cannot use namespace 'ProcessingTrigger' as a type.
src/app/money/rules/rule-edit/rule-edit.component.ts(75,31): error TS2709: Cannot use namespace 'ProcessingTrigger' as a type.
src/app/money/transaction-filter.service.ts(3,23): error TS2724: Module '"../../proto/model"' has no exported member 'ITransactionData'. Did you mean 'TransactionData'?
src/app/money/transactions/form-import/form-import.component.ts(4,32): error TS2724: Module '"../../../../proto/model"' has no exported member 'ITransactionData'. Did you mean 'TransactionData'?
src/app/money/transactions/form-import/format-mapping.ts(1,10): error TS2724: Module '"../../../../proto/model"' has no exported member 'ITransactionData'. Did you mean 'TransactionData'?
src/proto/model.d.ts(327,1): error TS1046: A 'declare' modifier is required for a top level declaration in a .d.ts file.
src/proto/model.d.ts(346,37): error TS2304: Cannot find name 'IBillingInfo'.
src/proto/model.d.ts(352,30): error TS2304: Cannot find name 'IBillingInfo'.
src/proto/model.d.ts(355,24): error TS2709: Cannot use namespace 'BillingType' as a type.
src/proto/model.d.ts(374,39): error TS2304: Cannot find name 'IBillingInfo'.
src/proto/model.d.ts(441,39): error TS2304: Cannot find name 'IDataContainer'.
:src/proto/model.d.ts(346,37): error TS2304: Cannot find name 'IBillingInfo'.
src/proto/model.d.ts(352,30): error TS2304: Cannot find name 'IBillingInfo'.
src/proto/model.d.ts(355,24): error TS2709: Cannot use namespace 'BillingType' as a type.
src/proto/model.d.ts(374,39): error TS2304: Cannot find name 'IBillingInfo'.
src/proto/model.d.ts(441,39): error TS2304: Cannot find name 'IDataContainer'.
src/proto/model.d.ts(447,30): error TS2304: Cannot find name 'IDataContainer'.
src/proto/model.d.ts(478,39): error TS2304: Cannot find name 'IDataContainer'.
src/proto/model.d.ts(649,37): error TS2304: Cannot find name 'IImportedRow'.
src/proto/model.d.ts(655,30): error TS2304: Cannot find name 'IImportedRow'.
src/proto/model.d.ts(674,39): error TS2304: Cannot find name 'IImportedRow'.
src/proto/model.d.ts(741,37): error TS2304: Cannot find name 'ITransaction'.
src/proto/model.d.ts(747,30): error TS2304: Cannot find name 'ITransaction'.
src/proto/model.d.ts(769,39): error TS2304: Cannot find name 'ITransaction'.
src/proto/model.d.ts(836,35): error TS2304: Cannot find name 'IGroupData'.
src/proto/model.d.ts(842,30): error TS2304: Cannot find name 'IGroupData'.
src/proto/model.d.ts(855,39): error TS2304: Cannot find name 'IGroupData'.
src/proto/model.d.ts(922,41): error TS2304: Cannot find name 'ITransactionData'.
src/proto/model.d.ts(928,30): error TS2304: Cannot find name 'ITransactionData'.
src/proto/model.d.ts(971,39): error TS2304: Cannot find name 'ITransactionData'.
src/proto/model.d.ts(1038,31): error TS2304: Cannot find name 'IMoney'.
src/proto/model.d.ts(1044,30): error TS2304: Cannot find name 'IMoney'.
src/proto/model.d.ts(1057,39): error TS2304: Cannot find name 'IMoney'.
src/proto/model.d.ts(1124,39): error TS2304: Cannot find name 'IGlobalComment'.
src/proto/model.d.ts(1130,30): error TS2304: Cannot find name 'IGlobalComment'.
src/proto/model.d.ts(1146,39): error TS2304: Cannot find name 'IGlobalComment'.
src/proto/model.d.ts(1213,38): error TS2304: Cannot find name 'IUserSettings'.
src/proto/model.d.ts(1219,30): error TS2304: Cannot find name 'IUserSettings'.
src/proto/model.d.ts(1124,39): error TS2304: Cannot find name 'IGlobalComment'.
src/proto/model.d.ts(1130,30): error TS2304: Cannot find name 'IGlobalComment'.
src/proto/model.d.ts(1146,39): error TS2304: Cannot find name 'IGlobalComment'.
src/proto/model.d.ts(1213,38): error TS2304: Cannot find name 'IUserSettings'.
src/proto/model.d.ts(1219,30): error TS2304: Cannot find name 'IUserSettings'.
src/proto/model.d.ts(1238,39): error TS2304: Cannot find name 'IUserSettings'.
src/proto/model.d.ts(1305,37): error TS2304: Cannot find name 'ILabelConfig'.
src/proto/model.d.ts(1311,30): error TS2304: Cannot find name 'ILabelConfig'.
src/proto/model.d.ts(1327,39): error TS2304: Cannot find name 'ILabelConfig'.
src/proto/model.d.ts(1394,40): error TS2304: Cannot find name 'IProcessingRule'.
src/proto/model.d.ts(1400,30): error TS2304: Cannot find name 'IProcessingRule'.
src/proto/model.d.ts(1403,22): error TS2709: Cannot use namespace 'ProcessingTrigger' as a type.
src/proto/model.d.ts(1425,39): error TS2304: Cannot find name 'IProcessingRule'.
src/proto/model.d.ts(1508,42): error TS2304: Cannot find name 'IProcessingAction'.
src/proto/model.d.ts(1514,30): error TS2304: Cannot find name 'IProcessingAction'.
src/proto/model.d.ts(1533,39): error TS2304: Cannot find name 'IProcessingAction'.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! finance-tracker@0.0.0 ng: `ng "build"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the finance-tracker@0.0.0 ng script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by Bone008** [comment]
Please run 
```
npm run protoc
```
once to generate the protocol buffer TypeScript definitions.
