### ISSUE TITLE
Bug: unexpected behavior of transactions with value of 0€ in analytics

### ISSUE THREAD

**Issue by Taimonania** [Bone008/finance-tracker#128]
Behavior: If a label has only transactions with a value of 0€, it is shown in analytics as "Expenses", but of course it doesn't have a piece in the pie chart. See label "intern+" or "leihe+,leihe+" in the below screenshot.

My expected behavior: only show labels that have some value other than 0€. It looks confusing to see a label in the list, but not in the pie chart.

Is this behavior intentional for some use-case?

![Screenshot_1](https://user-images.githubusercontent.com/15806049/59192398-94cd4280-8b82-11e9-98c5-d69e43828d60.png)

**Comment by Bone008** [comment]
Good catch. Not intentional and should be fixed. Also, the label deduplication seems to be broken with collapsed labels, the `leihe+,leihe+` category should show up as `leihe+` (if non-zero)
