### ISSUE TITLE
Analytics: not possible to "show more" and see the exact label

### ISSUE THREAD

**Issue by Taimonania** [Bone008/finance-tracker#129]
In this case I have two transactions under the label "intern/abheben" and one transaction under "extern/n26". I think it is unconsistent (and very unpractical) that "intern+" isn't expanded as well to "intern/abheben". Since I also can't click "Show more", I currently have to Alt-Click the pie-chart to see which label hides behind the "intern+". That is pretty annoying for a chart that should give a graphical overview ;)

![Screenshot_2](https://user-images.githubusercontent.com/15806049/59192739-b549cc80-8b83-11e9-8a3f-34584be5a69d.png)

**Comment by Taimonania** [comment]
I just saw that I have the same problem in "Expenses" in a more complex situation:

I have several transactions under "leben+" which don't have the exact same label. Some have the label "leben/essen/restaurant" and others "leben/essen/supermarkt". Shouldn't the "Show more" button  be enabled in this case?

![Screenshot_1](https://user-images.githubusercontent.com/15806049/59193243-51c09e80-8b85-11e9-9ee7-93ac88174088.png)

**Comment by Bone008** [comment]
You can use the "collapse child labels" control on the top of the page (directly under the filter input) to enable/disable the grouping of nested labels.

Note that only the top level can be controlled at the moment, so you cannot make a grouping `leben/essen+` right now. If you want that, please open a new ticket. 

The "show more" button is supposed to be used for controlling how many labels show up in the chart before the rest is put into the "other" category. For clarity I guess the buttons should be invisible if there is no "other" category at all.
