### ISSUE TITLE
Bug: shortcuts not working after click on checkbox

### ISSUE THREAD

**Issue by Taimonania** [Bone008/finance-tracker#182]
After clicking directly on the checkbox (see attached screenshot) I can't use e.g. the shortcut "G" to group the two transactions. Same for the other shortcuts, they don't work after a click on a checkbox. They start working again after a click anywhere else.

This behavior doesn't happen if I select the transaction by clicking somewhere else on the transaction.

![shortcut-bug](https://user-images.githubusercontent.com/15806049/73608574-0e5bea00-45c5-11ea-95f0-4bf2a1a41f26.png)

**Comment by Bone008** [comment]
Can reproduce. I need to disable shortcuts when an input element is focused, so you can type into text fields without triggering everything, but I suppose there should be an exception for checkboxes.
